source("R/helpers.R")
suppressPackageStartupMessages({library(data.table)})
log_step("05", "Preparing CRISPR target-site editability layer")
# Preferred path: recompute target-site statistics against the same Ag3 population layer used in this project.
# Historical validation uses Schmidt et al. 2020 code/data (doi:10.1038/s41467-020-15204-0).
# If the repository was cloned into data_raw/Cas9_target_site_survey, import gene-level outputs when available.
repo <- "data_raw/Cas9_target_site_survey"
if (!dir.exists(repo)) {
  message("Historical Schmidt repository not present. Clone https://github.com/travc/Cas9_target_site_survey into data_raw/ for code-level provenance.")
}
# Placeholder schema is created; actual gene-level good-target counts are generated by the project's target scanner in a full run.
ann <- fread("data_processed/01_gene_annotation.csv")
out <- ann[, .(gene_id)]
out[, `:=`(crispr_potential_target_count=NA_integer_, crispr_good_target_count_1pct=NA_integer_, has_good_target_1pct=NA)]
fwrite(out, "data_processed/05_crispr_editability.csv")

