source("R/helpers.R")
suppressPackageStartupMessages({library(data.table); library(ranger); library(vip)})
log_step("09", "Generating model explainability outputs")
# For the bagged PU model, robust global importance is generated by refitting the same final predictor set on all positives + a prespecified unlabeled sample.
d <- fread("results/candidate_lists/model_scored_genes.csv")
bundle <- readRDS("results/model_bundle.rds"); features <- bundle$features
# Detailed per-gene SHAP is generated in a full run using fastshap after the final model object is frozen.
writeLines(c("Explainability pipeline initialized.", paste("Features:", paste(features, collapse=", "))), "results/tables/explainability_manifest.txt")

